In [1]:
### A Pluto.jl notebook ###
# v0.19.27

using Markdown
using InteractiveUtils

# Get started with Julia - live

Before being able to run this notebook succesfully locally, you will need to [set up Julia and Pluto.](/Spring21/installation/)



## Variables

We can define a variable using `=` (assignment). Then we can use its value in other expressions:



In [2]:
x = 3

3

In [3]:
y = 2x

6

By default Julia displays the output of the last operation. (You can suppress the output by adding `;` (a semicolon) at the end.)



We can ask what type a variable has using `typeof`:


In [4]:
typeof(y)

Int64

## Functions


We can use a short-form, one-line function definition for simple functions:


In [5]:
f(x) = 2 + x

f (generic function with 1 method)

Typing the function's name gives information about the function. To call it we must use parentheses:


In [6]:
f

f (generic function with 1 method)

In [7]:
f(10)

12

For longer functions we use the following syntax with the `function` keyword and `end`:


In [8]:
function g(x, y)
	z = x + y
	return z^2
end

g (generic function with 1 method)

In [9]:
g(1, 2)

9

## For loops


Use `for` to loop through a pre-determined set of values:


In [10]:
let s = 0
	
	for i in 1:10
		s += i    # Equivalent to s = s + i
	end
	
	s
end

55

Here, `1:10` is a **range** representing the numbers from 1 to 10:


In [11]:
typeof(1:10)

UnitRange{Int64}

Above we used a `let` block to define a new local variable `s`. 
But blocks of code like this are usually better inside functions, so that they can be reused. For example, we could rewrite the above as follows:



In [12]:
function mysum(n)
	s = 0
	
	for i in 1:n
		s += i    
	end
	
	return s
end

mysum (generic function with 1 method)

In [13]:
mysum(100)

5050

## Conditionals: `if`


We can evaluate whether a condition is true or not by simply writing the condition:


In [14]:
a = 3

3

In [15]:
a < 5

true

We see that conditions have a Boolean (`true` or `false`) value. 

We can then use `if` to control what we do based on that value:


In [16]:
if a < 5
	"small"
	
else
	"big"
	
end

"small"

Note that the `if` also returns the last value that was evaluated, in this case the string `"small"` or `"big"`, Since Pluto is reactive, changing the definition of `a` above will automatically cause this to be reevaluated!


## Arrays


### 1D arrays (`Vector`s)


We can make a `Vector` (1-dimensional, or 1D array) using square brackets:


In [17]:
v = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [18]:
typeof(v)

Vector{Int64} (alias for Array{Int64, 1})

The `1` in the type shows that this is a 1D array.

We access elements also using square brackets:


In [19]:
v[2]

2

In [20]:
v[2] = 10

10

Note that Pluto does not automatically update cells when you modify elements of an array, but the value does change.


A nice way to create `Vector`s following a certain pattern is to use an **array comprehension**:


In [21]:
v2 = [i^2 for i in 1:10]

10-element Vector{Int64}:
   1
   4
   9
  16
  25
  36
  49
  64
  81
 100

### 2D arrays (matrices)


We can make small matrices (2D arrays) with square brackets too:


In [22]:
M = [1 2
	 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [23]:
typeof(M)

Matrix{Int64} (alias for Array{Int64, 2})

The `2` in the type confirms that this is a 2D array.


This won't work for larger matrices, though. For that we can use e.g.


In [24]:
zeros(5, 5)

5×5 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

Note that `zeros` gives `Float64`s by default. We can also specify a type for the elements:


In [25]:
zeros(Int, 4, 5)

4×5 Matrix{Int64}:
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0

We can then fill in the values we want by manipulating the elements, e.g. with a `for` loop.


A nice alternative syntax to create matrices following a certain pattern is an array comprehension with a *double* `for` loop:


In [26]:
[i + j for i in 1:5, j in 1:6]

5×6 Matrix{Int64}:
 2  3  4  5   6   7
 3  4  5  6   7   8
 4  5  6  7   8   9
 5  6  7  8   9  10
 6  7  8  9  10  11


# Acknowledgement




		
_**Computational Thinking**, a live online Julia/Pluto textbook._ ([computationalthinking.mit.edu](https://computationalthinking.mit.edu), [original notebook](https://github.com/mitmath/18S191/blob/Fall20/lecture_notebooks/Basic%20Julia%20syntax.jl))

